require 'rake'
require 'json'
require 'cucumber'
require 'csl'

module CSL
  module TestSuite

    # The test expectations are based on the locales used by citeproc-js;
    # use the version of the locales its 'locale' submodule points to.
    # Update this together with the test-suite.
    LOCALES = '195bef843f87fc917be45ab3eca60536e4ef4626'.freeze

    # Only the locales needed by the tests are copied here
    LOCALES_PATH = 'features/support/locales'.freeze

    NON_STANDARD = %{
      quotes_PunctuationWithInnerQuote            # replaces single quotes and apostrophes
      sort_SubstituteTitle                        # ---
      substitute_SuppressOrdinaryVariable         # citeproc-js bug?
      sort_FamilyOnly                             # invalid CSL (no layout) / ANZ after Aardvark?
      name_ParticleCaps3                          # " in family name
      testers_SecondAutoGeneratedZoteroPluginTest # uses <sc> for small-caps
      name_ParticleCaps2                          # capitalizes particle of first name
      magic_SecondFieldAlign                      #
      magic_CitationLabelInBibliography           # Citation labels
      label_EditorTranslator1                     # ?
      display_SecondFieldAlignMigratePunctuation  # format
      flipflop_ItalicsWithOk                      # HTML in input
      flipflop_ItalicsWithOkAndTextcase           # ---
      variables_TitleShortOnShortTitleNoTitle     # converts shortTitle to title-short
      textcase_Uppercase                          # no-case input markup
      textcase_TitleCapitalization                # ---
      textcase_SentenceCapitalization             # ---
      textcase_Lowercase                          # ---
      textcase_CapitalizeFirstWithDecor           # ---
      textcase_CapitalizeFirst                    # ---
      textcase_CapitalizeAll                      # ---
      textcase_SkipNameParticlesInTitleCase       #
      magic_SuperscriptChars                      # converts superscript characters to <sup>
      bugreports_NumberAffixEscape                # ---
      decorations_Baseline                        # uses style="baseline"
      date_DateNoDateNoTest                       # citeproc-js error message
      substitute_SubstituteOnlyOnceTermEmpty      # empty term used as substitute
      number_LimitOrdinalsToDayOne                # dates in note field
      variables_ContainerTitleShort2              # variables in note field
      fullstyles_ABdNT                            # en dash in issue range
      number_OrdinalSpacing                       # ordinals in non-numeric text
    }.scan(/^\s*(\S+)/).flatten

    module_function

    def load(file)
      JSON.parse(File.open(file, 'r:UTF-8').read)
    end

    # @param tags [Array<String>] the default locales used by the tests
    # @return [Array<String>] the locales needed, including fallbacks
    def locales_for(tags)
      locales = tags.flat_map do |tag|
        tag = CSL::Locale.normalize(tag.sub(/-[a-z0-9]-.*\z/i, ''))
        [tag, CSL::Locale.normalize(tag.split('-')[0]), CSL::Locale.default]
      rescue ArgumentError
        [CSL::Locale.default]
      end

      locales.uniq
    end

    def tags_for(json, feature, name)
      tags = []

      tags << "@#{json['mode']}"
      tags << "@#{feature}"

      tags << '@bibsection' if json['bibsection']
      tags << '@citation-items' if json['citation_items']

      if NON_STANDARD.include? "#{feature}_#{name}"
        tags << '@non-standard'
      end

      tags.uniq
    end

  end
end

namespace :test do

  desc 'Fetch the CSL test-suite repository and locales'
  task :init => [:clean] do
    system "git clone --depth 1 https://github.com/citation-style-language/test-suite.git test"

    system "git init -q test/locales"
    system "git -C test/locales fetch -q --depth 1 https://github.com/citation-style-language/locales.git #{CSL::TestSuite::LOCALES}"
    system "git -C test/locales checkout -q FETCH_HEAD"
  end

  desc 'Remove the CSL test-suite repository and locales'
  task :clean do
    FileUtils.rm_r 'test' if File.directory?('test')
  end

  desc 'Delete all generated CSL feature tests'
  task :clear do
    Dir['features/**/*'].sort.reverse.each do |path|
      unless path =~ /features\/(support|step_definitions)/
        if File.directory?(path)
          system "rmdir #{path}"
        else
          system "rm #{path}"
        end
      end
    end
  end

  desc 'Convert the processor tests to Cucumber features'
  task :convert => [:clear] do
    features = Dir['test/processor-tests/machines/*.json'].group_by { |path|
      File.basename(path).split(/_/, 2)[0]
    }

    locales = []

    features.each_key do |feature|
      system "mkdir features/#{feature}"

      features[feature].each do |file|
        json, name = CSL::TestSuite.load(file), File.basename(file, '.json').split(/_/, 2)[-1]

        # Citations and bibentries inputs are not supported
        next if json['citations'] || json['bibentries']

        locales << (json['csl'][/default-locale="([^"]+)"/, 1] || CSL::Locale.default)

        tags = CSL::TestSuite.tags_for(json, feature, name)

        # Apply some filters
        json['result'].gsub!('&#38;', '&amp;')

        File.open("features/#{feature}/#{name}.feature", 'w:UTF-8') do |out|
          out << "Feature: #{feature}\n"
          out << "  As a CSL cite processor hacker\n"
          out << "  I want the test #{File.basename(file, '.json')} to pass\n\n"
          out << "  " << tags.join(' ') << "\n"
          out << "  Scenario: #{name.gsub(/([[:lower:]])([[:upper:]])/, '\1 \2')}\n"

          out << "    Given the following style:\n"
          out << "    \"\"\"\n"

          json['csl'].each_line do |line|
            out << '    ' << line
          end
          out << "\n    \"\"\"\n"

          out << "    And the following input:\n"
          out << "    \"\"\"\n"
          out << "    " << JSON.dump(json['input']) << "\n"
          out << "    \"\"\"\n"


          if json['abbreviations']
            out << "    And the following abbreviations:\n"
            out << "    \"\"\"\n"
            out << "    " << JSON.dump(json['abbreviations']) << "\n"
            out << "    \"\"\"\n"
          end

          case json['mode']
          when 'citation'
            if json['citation_items']
              out << "    When I cite the following items:\n"
              out << "    \"\"\"\n"
              out << "    " << JSON.dump(json['citation_items']) << "\n"
              out << "    \"\"\"\n"
              out << "    Then the results should be:\n"

              lines = json['result'].each_line.to_a
              padding = lines.max.length

              lines.each do |line|
                out << ("      | %-#{padding}s |\n" % line.strip)
              end

            else
              out << "    When I cite all items\n"
              out << "    Then the result should be:\n"
              out << "    \"\"\"\n"
              json['result'].each_line do |line|
                out << "    " << line.strip << "\n"
              end
              out << "    \"\"\"\n"
            end


          when 'bibliography-header'
            out << "    When I render the entire bibliography\n"
            out << "    Then the bibliography's options should match:\n"

            headers = Hash[json['result'].each_line.map { |s| s.split(/:\s*/, 2) }]

            out << "      | entry-spacing | line-spacing |\n"
            out << ("      | %s             | %s            |\n" % [headers['entryspacing'].strip, headers['linespacing'].strip])

          when 'bibliography'

            if json['bibsection']
              out << "    When I render the following bibliography selection:\n"
              out << "    \"\"\"\n"
              out << "    " << JSON.dump(json['bibsection']) << "\n"
              out << "    \"\"\"\n"
            else
              out << "    When I render the entire bibliography\n"
            end

            out << "    Then the bibliography should be:\n"
            out << "    \"\"\"\n"
            json['result'].each_line do |line|
              out << '    ' << line
            end
            out << "\n    \"\"\"\n"
          end
        end
      end
    end

    # Copy the locales needed by the tests
    FileUtils.mkdir_p CSL::TestSuite::LOCALES_PATH
    FileUtils.rm Dir["#{CSL::TestSuite::LOCALES_PATH}/locales-*.xml"]

    CSL::TestSuite.locales_for(locales).each do |tag|
      file = "test/locales/locales-#{tag}.xml"
      system "cp #{file} #{CSL::TestSuite::LOCALES_PATH}" if File.exist?(file)
    end
  end


end
